### ISSUE TITLE
career centre to-dos

### ISSUE THREAD

**Issue by SorenRajani** [W4S-2021/workathon-handbook#4]
stuff we need to do
- [x] Make A concrete incentive proposal (sponsor pay per # of entries with an upper bound)
- [x] Give them NDA's 
- [x] add in career centre team to discord server
- [x] email + cc mauricio figuring out who wants to ping corey
- [x] payment processing: vseus or vsecc
- [x] email Erin about VSEUS marketing external
- [x] look into VSEUS grant if showpass takes a cut (to cover showpass costs)

stuff they need to do
- [x] Nancy gets back to us on payment processing
- [x] Staff will spread marketing material 
- [x] Staff will handle NDA signing

**Comment by aadsouza** [comment]
- [ ] add in career centre team to discord server

**Comment by SorenRajani** [comment]
Career centre will:
-[ ] Nancy gets back to us on payment processing
-[ ] Staff will spread marketing material 
-[ ] Staff will handle NDA signing

**Comment by SorenRajani** [comment]
Added comments will be compiled to the top list then deleted
