### ISSUE TITLE
Mapinator

### ISSUE THREAD

**Issue by jbrightuniverse** [W4S-2021/workathon-handbook#8]
- [x] cumulative new entry count
- [ ] logos on the page
- [x] Leaderboard

**Comment by VoliCrank** [comment]
Which logos should I put? I will put them up later this week. Also for cumulative new entry count, do we want to have a goal number?

**Comment by aadsouza** [comment]
@VoliCrank those would be ex-post after we hear back from donors about what tier they want to be on.. also, maybe no goal number.. we also need to add the absolute rank stuff
